### ISSUE TITLE
レイアウトの変更

### ISSUE THREAD

**Issue by kayano44** [kayano44/iniad-fake-homepage#5]

**Comment by kayano44** [comment]
p tagの上下左右幅調整

**Comment by toda-004** [comment]
相談です。
コンセプトページに配置した画像(.conseptimage)をセンターに配置したいんですが、できない...
cssで「 text-align: center;」って入力たけど、動かない...
ちなみに「left」でも同じ位置。
「right」だと、文字と同じグループにくくられて変な右側に動いちゃう(ToT)

よろしくお願いします...

**Comment by kayano44** [comment]
インライン要素として左詰になってしまうので、ブロック要素に変換してマージンを取ってみました！

**Comment by toda-004** [comment]
さすがです！
.conseptimageの配置設定は削除しときます！
